# Generated by Django 4.0.6 on 2022-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ushindi_app', '0004_alter_testimony_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='image',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('Current Child', 'Current Child')], default='Alumni', max_length=13),
        ),
    ]
