# Generated by Django 4.0.6 on 2022-11-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ushindi_app', '0005_remove_testimony_image_alter_testimony_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypics',
            name='album',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='GalleryPics',
        ),
    ]
