# Generated by Django 4.0.6 on 2022-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('status', models.CharField(choices=[('Alumni', 'Alumni'), ('Current Child', 'Current Child')], default='Alumni', max_length=13)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
