# Generated by Django 4.0.6 on 2022-09-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ushindi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='vids',
            field=models.FileField(default=False, upload_to='videos'),
        ),
    ]
