# Generated by Django 4.0.6 on 2022-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ushindi', '0003_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='proj_pic')),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=113)),
            ],
        ),
        migrations.CreateModel(
            name='FutureProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='proj_pic')),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=113)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='proj_pic')),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=113)),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
