# Generated by Django 4.0.6 on 2022-09-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ushindi', '0004_currentprojects_futureprojects_previousprojects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.FileField(default='default.jpg', upload_to='proj_pic')),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=113)),
            ],
        ),
        migrations.CreateModel(
            name='ProjDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('images', models.FileField(upload_to='pics')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_ushindi.projevents')),
            ],
        ),
    ]
