# Generated by Django 4.0.6 on 2022-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ushindi', '0005_projevents_projdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='vids',
        ),
        migrations.AlterField(
            model_name='projdetails',
            name='content',
            field=models.TextField(default=False),
        ),
    ]
