# Generated by Django 4.0.6 on 2022-09-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ushindi', '0006_remove_testimony_vids_alter_projdetails_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.FileField(default='default.jpg', upload_to='profile_pic')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='ProjDetails',
        ),
        migrations.DeleteModel(
            name='ProjEvents',
        ),
        migrations.AddField(
            model_name='projectpics',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_ushindi.projects'),
        ),
    ]
