# Generated by Django 4.0.6 on 2022-08-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
