# Generated by Django 4.0.6 on 2022-08-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tes', '0002_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
