# Generated by Django 4.0.6 on 2022-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tes', '0003_alter_testimony_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='status',
            field=models.IntegerField(choices=[(0, 'Alumni'), (1, 'Current Child')], default=0),
        ),
    ]
