# Generated by Django 4.0.6 on 2022-08-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tes', '0004_testimony_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('Current Child', 'Current Child')], default='Alumni', max_length=13),
        ),
    ]
