# Generated by Django 4.0.6 on 2022-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ushindi_app', '0002_album_gallerypics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Future', 'Future')], default='Current', max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.FileField(default='default.jpg', upload_to='profile_pic')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
