# Generated by Django 4.0.6 on 2022-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pic1', models.ImageField(default='default.jpg', upload_to='Rafiki')),
            ],
        ),
    ]
