# Generated by Django 4.0.6 on 2022-08-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_photos', '0003_remove_galleryposter_pic_photogallery_albumpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RafikiGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pic2', models.ImageField(default='default.jpg', upload_to='Rafiki')),
                ('albumpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_photos.galleryposter')),
            ],
        ),
    ]
