# Generated by Django 4.0.6 on 2022-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photos', '0007_newalbums_remove_albumimage_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newalbums',
            name='pictur1',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='newalbums',
            name='pictur2',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='newalbums',
            name='pictur3',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='newalbums',
            name='pictur4',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AlterField(
            model_name='newalbums',
            name='pictur',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
    ]
