# Generated by Django 4.0.6 on 2022-08-18 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_photos', '0008_newalbums_pictur1_newalbums_pictur2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryposter',
            name='alt',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='galleryposter',
            name='pictr',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='galleryposter',
            name='pictr1',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='galleryposter',
            name='pictr2',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='galleryposter',
            name='pictr3',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='galleryposter',
            name='pictr4',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
    ]
