# Generated by Django 4.0.6 on 2022-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photos', '0010_remove_galleryposter_pictr1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryposter',
            name='pictr',
        ),
        migrations.AddField(
            model_name='newalbums',
            name='pictur5',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
        migrations.AddField(
            model_name='newalbums',
            name='pictur6',
            field=models.ImageField(default='default.jpg', upload_to='all_pics'),
        ),
    ]
