# Generated by Django 4.0.6 on 2022-08-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpics',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_pho.album'),
        ),
    ]
