# Generated by Django 4.0.6 on 2022-10-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ushindi_app', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('In Home', 'In Home')], default='Alumni', max_length=13),
        ),
    ]
